web:
  build: web
  command: /usr/bin/supervisord
  ports:
    - "80:80"
  volumes:
    - source:/app
    - .:/workspace
  environment:
    RUN_MODE: devel
  links:
    - db:DB_SERVER
    - cache:CACHE_SERVER

db:
  image: mysql
  #ports: 
  #  - "3306:3306"
  #volumes:
  #  - dbdata:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: 123456
    MYSQL_USER: kufa
    MYSQL_PASSWORD: 654321
    MYSQL_DATABASE: kufa

  # 指定数据库密码 和 数据存在地址

cache:
  image: redis
  ports: 
    - "6379:6379"
  volumes:
    - cachedata:/data

# vim: ts=2 sw=2

