export EDITOR=vim
export PAGER='less'
export PYTHONDONTWRITEBYTECODE=1

export PATH=$PATH:~/bin
export LD_LIBRARY_PATH=/usr/local/lib:/usr/lib

#export JAVA_HOME=/home/reedboat/java/current
#export JRE_HOME=${JAVA_HOME}/jre
#export CLASSPATH=$HADOOP_HOME/lib:$JAVA_HOME/lib:$JRE_HOME/lib

export HOSTSHORT=`hostname`
export OS=`uname`;
export LC_ALL='en_US.UTF-8'
export LANG='en_US.UTF-8'

export EDITOR='vim'
export SVN_EDITOR=vim

if [[ -z "$ZSH" ]]
then
    if [ "$PS1" ]
    then
        if [ -f /etc/bash_completion ]
        then
            if [ -r /etc/bash_completion ]
            then
                . /etc/bash_completion
            fi
        fi
    fi
fi

if [ -f ~/.markrc ]; then
        . ~/.markrc
fi


function run_cmd_with_password {
    expect -c "\
    set timeout 90
    set env(TERM)
    spawn $1
    expect \"password:\"
    send $2\r
    expect eof
  "
}

function interact_cmd_with_password {
    expect -c "\
    set timeout 90
    set env(TERM)
    spawn $1
    expect \"password:\"
    send $2\r
    interact
  "
}

